"""
chatbot.py
----------
AI Chatbot + Natural Language Analytics.

Works with zero configuration using a built-in rule-based analyzer.
If the user supplies their own Anthropic or OpenAI API key in the
sidebar, responses are generated by that model instead for richer,
free-form answers. No key is ever hardcoded here.
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import re


def _strongest_correlation_pair(df: pd.DataFrame, num_cols: list):
    """Returns (col_a, col_b, abs_corr_value) for the strongest pairwise
    correlation, or None if it can't be computed. Works purely with numpy
    arrays to avoid pandas Copy-on-Write read-only buffer issues."""
    if len(num_cols) < 2:
        return None
    corr = df[num_cols].corr(numeric_only=True).abs()
    arr = corr.to_numpy(copy=True)
    if arr.size == 0:
        return None
    np.fill_diagonal(arr, 0)
    idx = np.unravel_index(np.argmax(arr), arr.shape)
    value = arr[idx]
    if not np.isfinite(value):
        return None
    return corr.index[idx[0]], corr.columns[idx[1]], float(value)


# ---------------------------------------------------------------------------
# Rule-based fallback "AI" — works with no API key at all
# ---------------------------------------------------------------------------
def _dataset_profile(df: pd.DataFrame) -> str:
    num_cols = df.select_dtypes(include=np.number).columns.tolist()
    cat_cols = df.select_dtypes(include="object").columns.tolist()
    missing = int(df.isna().sum().sum())
    dup = int(df.duplicated().sum())

    lines = [
        f"- **Shape:** {df.shape[0]:,} rows × {df.shape[1]} columns",
        f"- **Numeric columns ({len(num_cols)}):** {', '.join(num_cols[:8]) or 'none'}",
        f"- **Categorical columns ({len(cat_cols)}):** {', '.join(cat_cols[:8]) or 'none'}",
        f"- **Missing values:** {missing:,} ({round(missing / df.size * 100, 2) if df.size else 0}% of cells)",
        f"- **Duplicate rows:** {dup:,}",
    ]
    pair = _strongest_correlation_pair(df, num_cols)
    if pair:
        lines.append(f"- **Strongest correlation:** {pair[0]} ↔ {pair[1]} ({pair[2]:.2f})")
    return "\n".join(lines)


def generate_ai_summary(df: pd.DataFrame) -> str:
    provider = st.session_state.get("api_provider", "None (built-in insights)")
    if provider != "None (built-in insights)" and st.session_state.get("api_key"):
        prompt = (
            "You are a senior data analyst. Given this dataset profile, write a concise "
            "business-ready summary (5-8 bullet points) covering data quality, notable "
            "patterns, and 2-3 recommended next analysis steps.\n\n"
            f"Dataset profile:\n{_dataset_profile(df)}\n\n"
            f"Column names and dtypes:\n{df.dtypes.astype(str).to_dict()}"
        )
        result = _call_external_llm(prompt)
        if result:
            return result
    # Fallback
    num_cols = df.select_dtypes(include=np.number).columns.tolist()
    quality_notes = []
    missing = df.isna().sum()
    worst = missing[missing > 0].sort_values(ascending=False)
    if not worst.empty:
        quality_notes.append(f"Column **{worst.index[0]}** has the most missing values ({int(worst.iloc[0])}).")
    if df.duplicated().sum() > 0:
        quality_notes.append(f"There are **{int(df.duplicated().sum())}** duplicate rows worth reviewing.")
    if num_cols:
        skewed = df[num_cols].skew(numeric_only=True).abs().sort_values(ascending=False)
        if not skewed.empty and skewed.iloc[0] > 1:
            quality_notes.append(f"Column **{skewed.index[0]}** is highly skewed (skew={skewed.iloc[0]:.2f}) — consider a log transform.")

    return (
        "### 🤖 AI Summary (built-in analyzer)\n\n"
        f"{_dataset_profile(df)}\n\n"
        "**Observations:**\n" + ("\n".join(f"- {n}" for n in quality_notes) if quality_notes else "- No major data quality issues detected.") +
        "\n\n**Recommended next steps:**\n"
        "- Review and treat missing values / duplicates flagged above.\n"
        "- Explore correlations between numeric features for feature engineering.\n"
        "- Build a dashboard with the Dashboard Builder to visualize key trends.\n\n"
        "_Tip: add an Anthropic or OpenAI API key in the sidebar for richer, free-form AI insights._"
    )


def _call_external_llm(prompt: str) -> str:
    provider = st.session_state.get("api_provider")
    api_key = st.session_state.get("api_key")
    try:
        if provider == "Anthropic (Claude)":
            import anthropic
            client = anthropic.Anthropic(api_key=api_key)
            resp = client.messages.create(
                model="claude-sonnet-4-6",
                max_tokens=800,
                messages=[{"role": "user", "content": prompt}],
            )
            return "".join(block.text for block in resp.content if hasattr(block, "text"))
        elif provider == "OpenAI (GPT)":
            from openai import OpenAI
            client = OpenAI(api_key=api_key)
            resp = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                max_tokens=800,
            )
            return resp.choices[0].message.content
    except Exception as e:
        st.warning(f"External AI call failed, falling back to built-in analyzer. ({e})")
        return ""
    return ""


# ---------------------------------------------------------------------------
# Chat Q&A
# ---------------------------------------------------------------------------
def answer_question(df: pd.DataFrame, question: str) -> str:
    provider = st.session_state.get("api_provider", "None (built-in insights)")
    if provider != "None (built-in insights)" and st.session_state.get("api_key"):
        prompt = (
            "You are a data analytics assistant embedded in a dashboard app called Pycleansheet AI. "
            f"The user's dataset profile:\n{_dataset_profile(df)}\n\n"
            f"Sample rows:\n{df.head(5).to_string()}\n\n"
            f"User question: {question}\n"
            "Answer concisely and practically."
        )
        result = _call_external_llm(prompt)
        if result:
            return result

    q = question.lower()
    num_cols = df.select_dtypes(include=np.number).columns.tolist()
    cat_cols = df.select_dtypes(include="object").columns.tolist()

    if "summar" in q:
        return generate_ai_summary(df)
    if "correlat" in q:
        if len(num_cols) < 2:
            return "There aren't enough numeric columns to compute correlations."
        pair = _strongest_correlation_pair(df, num_cols)
        if not pair:
            return "Could not compute a meaningful correlation for this dataset."
        return f"The strongest correlation is between **{pair[0]}** and **{pair[1]}** ({pair[2]:.2f})."
    if "missing" in q or "null" in q:
        missing = df.isna().sum()
        missing = missing[missing > 0].sort_values(ascending=False)
        if missing.empty:
            return "Good news — there are no missing values in this dataset."
        return "Missing values by column:\n" + "\n".join(f"- {c}: {v}" for c, v in missing.items())
    if "duplicate" in q:
        return f"There are **{int(df.duplicated().sum())}** duplicate rows in the dataset."
    if "trend" in q or "pattern" in q:
        if num_cols:
            col = num_cols[0]
            return f"Looking at **{col}**, the mean is {df[col].mean():.2f}, ranging from {df[col].min():.2f} to {df[col].max():.2f}."
        return "Add numeric columns to identify trends."
    if "recommend" in q and "visual" in q:
        return (
            "Based on your columns, I'd recommend:\n"
            f"- A **bar chart** comparing `{cat_cols[0]}` vs `{num_cols[0]}`\n" if cat_cols and num_cols else ""
        ) + "- A **correlation heatmap** for numeric relationships\n- A **histogram** to see distributions"
    if "preprocess" in q:
        return "Consider: filling/removing missing values, removing duplicates, scaling numeric features, and encoding categorical columns — all available in the Data Cleaning Studio."
    if "business" in q:
        return generate_ai_summary(df)

    return (
        "I can help with dataset summaries, correlations, missing values, duplicates, trends, "
        "visualization recommendations, preprocessing advice, and business insights. Try asking "
        "something like *'summarize this dataset'* or *'explain the correlation'*."
    )


# ---------------------------------------------------------------------------
# Natural Language → chart generation
# ---------------------------------------------------------------------------
def nl_to_chart(df: pd.DataFrame, text: str):
    """Very lightweight NL parser: 'show X by Y', 'compare X by Y',
    'distribution of X', 'top N X' patterns → returns a plotly figure or None."""
    text_l = text.lower().strip()
    cols = {c.lower(): c for c in df.columns}
    num_cols = df.select_dtypes(include=np.number).columns.tolist()

    def find_col(fragment):
        for lc, orig in cols.items():
            if lc in fragment:
                return orig
        return None

    m = re.search(r"(top\s+(\d+))\s+(.*)", text_l)
    if m:
        n = int(m.group(2))
        target_frag = m.group(3)
        target_col = find_col(target_frag)
        if target_col:
            vc = df[target_col].value_counts().head(n).reset_index()
            vc.columns = [target_col, "count"]
            fig = px.bar(vc, x=target_col, y="count", title=f"Top {n} {target_col}")
            fig.update_layout(template="plotly_dark")
            return fig

    if "distribution" in text_l:
        target_col = find_col(text_l.replace("distribution", "").replace("of", ""))
        if target_col and target_col in num_cols:
            fig = px.histogram(df, x=target_col, title=f"Distribution of {target_col}", marginal="box")
            fig.update_layout(template="plotly_dark")
            return fig

    m = re.search(r"(show|compare)\s+(.*?)\s+by\s+(.*)", text_l)
    if m:
        metric_frag, group_frag = m.group(2), m.group(3)
        metric_col = find_col(metric_frag) or (num_cols[0] if num_cols else None)
        group_col = find_col(group_frag)
        if metric_col and group_col:
            if pd.api.types.is_numeric_dtype(df[metric_col]):
                agg = df.groupby(group_col)[metric_col].sum().reset_index().sort_values(metric_col, ascending=False).head(25)
                fig = px.bar(agg, x=group_col, y=metric_col, title=f"{metric_col} by {group_col}", color=metric_col, color_continuous_scale="Purples")
            else:
                agg = df.groupby(group_col)[metric_col].count().reset_index().rename(columns={metric_col: "count"})
                fig = px.bar(agg, x=group_col, y="count", title=f"Count of {metric_col} by {group_col}")
            fig.update_layout(template="plotly_dark")
            return fig

    return None
